import React, { useEffect, useMemo, useState } from "react";
import { Avatar, Box, Dialog, DialogContent, InputAdornment, List, ListItemButton, ListItemIcon, ListItemText, TextField, Typography } from "@mui/material";
import SearchIcon from "@mui/icons-material/Search"; import DashboardOutlinedIcon from "@mui/icons-material/DashboardOutlined"; import TaskAltOutlinedIcon from "@mui/icons-material/TaskAltOutlined"; import FolderOutlinedIcon from "@mui/icons-material/FolderOutlined"; import InsightsOutlinedIcon from "@mui/icons-material/InsightsOutlined"; import SettingsOutlinedIcon from "@mui/icons-material/SettingsOutlined"; import AddTaskOutlinedIcon from "@mui/icons-material/AddTaskOutlined"; import { searchApi } from "../api";
export default function CommandPalette({open,onClose,todos=[],projects=[],users=[],onNavigate,onNewTask,onOpenTask,onSelectProject}){
 const [query,setQuery]=useState("");const [remote,setRemote]=useState(null);useEffect(()=>{if(open){setQuery("");setRemote(null);setTimeout(()=>document.getElementById("taskflow-command-input")?.focus(),20)}},[open]);
 useEffect(()=>{if(query.trim().length<2){setRemote(null);return;}const id=setTimeout(()=>searchApi(query).then(r=>setRemote(r.data)).catch(()=>setRemote(null)),220);return()=>clearTimeout(id)},[query]);
 const items=useMemo(()=>{const q=query.trim().toLowerCase();const pages=[{id:"dashboard",label:"Ouvrir le tableau de bord",hint:"Vue d’ensemble",icon:<DashboardOutlinedIcon/>,action:()=>onNavigate("dashboard")},{id:"tâches",label:"Ouvrir les tâches",hint:"Toutes les tâches",icon:<TaskAltOutlinedIcon/>,action:()=>onNavigate("tâches")},{id:"projects",label:"Ouvrir les projets",hint:"Espace de travail",icon:<FolderOutlinedIcon/>,action:()=>onNavigate("projects")},{id:"analytics",label:"Ouvrir les analyses",hint:"Indicateurs",icon:<InsightsOutlinedIcon/>,action:()=>onNavigate("analytics")},{id:"settings",label:"Ouvrir les paramètres",hint:"Préférences",icon:<SettingsOutlinedIcon/>,action:()=>onNavigate("settings")},{id:"new",label:"Créer une nouvelle tâche",hint:"Action",icon:<AddTaskOutlinedIcon/>,action:onNewTask}];if(remote){return [...(remote.tasks||[]).map(t=>({id:`task-${t.id}`,label:t.title,hint:`Tâche · ${t.projectName||""}`,icon:<TaskAltOutlinedIcon/>,action:()=>onOpenTask(t)})),...(remote.projects||[]).map(p=>({id:`project-${p.id}`,label:p.name,hint:"Projet",icon:<FolderOutlinedIcon/>,action:()=>{onSelectProject(p.id);onNavigate("projects")}})),...(remote.users||[]).map(u=>({id:`user-${u.id}`,label:u.name,hint:u.email||"Membre",icon:<Avatar sx={{width:26,height:26}}>{u.name?.[0]}</Avatar>,action:()=>onNavigate("users")}))].slice(0,12)}const all=[...pages,...projects.map(p=>({id:`project-${p.id}`,label:p.name,hint:"Projet",icon:<FolderOutlinedIcon/>,action:()=>{onSelectProject(p.id);onNavigate("projects")}})),...todos.map(t=>({id:`task-${t.id}`,label:t.title,hint:`Tâche · ${t.status||"todo"}`,icon:<TaskAltOutlinedIcon/>,action:()=>onOpenTask(t)})),...users.map(u=>({id:`user-${u.id}`,label:u.name,hint:u.email||"Membre",icon:<Avatar sx={{width:26,height:26}}>{u.name?.[0]}</Avatar>,action:()=>onNavigate("users")}))];return(q?all.filter(x=>`${x.label} ${x.hint}`.toLowerCase().includes(q)):all.slice(0,12)).slice(0,12)},[query,remote,todos,projects,users,onNavigate,onNewTask,onOpenTask,onSelectProject]);
 return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm" PaperProps={{sx:{borderRadius:3,overflow:"hidden"}}}><DialogContent sx={{p:0}}><TextField id="taskflow-command-input" fullWidth autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans TaskFlow…" InputProps={{startAdornment:<InputAdornment position="start"><SearchIcon/></InputAdornment>,sx:{borderRadius:0,'& fieldset':{border:0},py:1}}}/><Box sx={{px:2,pb:1}}><Typography variant="caption" color="text.secondary">⌘K / Ctrl K · La recherche utilise les données locales</Typography></Box><List sx={{px:1,pb:1,maxHeight:520,overflow:"auto"}}>{items.map(item=><ListItemButton key={item.id} onClick={()=>{item.action?.();onClose()}} sx={{borderRadius:2,mb:.25}}><ListItemIcon sx={{minWidth:42}}>{item.icon}</ListItemIcon><ListItemText primary={item.label} secondary={item.hint}/></ListItemButton>)}{!items.length&&<Box sx={{p:3,textAlign:"center"}}><Typography fontWeight={800}>Aucun résultat</Typography><Typography variant="body2" color="text.secondary">Essayez une autre recherche.</Typography></Box>}</List></DialogContent></Dialog>;
}
