import React, { useEffect, useState } from "react";
import { Avatar, Box, Button, Card, CardContent, Chip, Divider, IconButton, Stack, Tabs, Tab, Typography } from "@mui/material";
import DoneAllIcon from "@mui/icons-material/DoneAll";
import MarkEmailUnreadOutlinedIcon from "@mui/icons-material/MarkEmailUnreadOutlined";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import { getNotificationsApi, markAllNotificationsReadApi, markNotificationReadApi } from "../api";
export default function Inbox({ onOpenTask }) { const [tab,setTab]=useState("all"); const [rows,setRows]=useState([]);
 const load=()=>getNotificationsApi({limit:100,...(tab!=="all"&&tab!=="unread"?{type:tab}:{}) ,...(tab==="unread"?{unread:true}:{})}).then(r=>setRows(r.data||[])).catch(()=>{});
 useEffect(()=>{load()},[tab]); const unread=rows.filter(x=>!x.read).length;
 const read=async n=>{try{await markNotificationReadApi(n.id);setRows(x=>x.map(v=>v.id===n.id?{...v,read:true}:v));}catch(_){} if(n.taskId)onOpenTask?.(n.task||{id:n.taskId,title:n.message});};
 const readAll=async()=>{try{await markAllNotificationsReadApi();setRows(x=>x.map(v=>({...v,read:true})));}catch(_){} };
 return <Stack spacing={3}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between"><Box><Typography variant="h4" fontWeight={900}>Boîte de réception</Typography><Typography color="text.secondary">Tâches, échéances et notifications de collaboration</Typography></Box><Button startIcon={<DoneAllIcon/>} onClick={readAll} disabled={!unread}>Tout marquer comme lu</Button></Stack><Card><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab value="all" label="Toutes"/><Tab value="unread" label={`Non lues ${unread||""}`}/><Tab value="task_assigned" label="Assignées"/><Tab value="comment" label="Commentaires"/><Tab value="project_member" label="Projets"/></Tabs></Card><Card><CardContent sx={{p:0}}>{rows.length?rows.map((n,i)=><React.Fragment key={n.id}><Stack direction="row" spacing={2} alignItems="center" sx={{p:2.25,opacity:n.read?.62:1}}><Avatar variant="rounded"><MarkEmailUnreadOutlinedIcon/></Avatar><Box sx={{flex:1,minWidth:0}}><Stack direction="row" spacing={1}><Typography fontWeight={n.read?600:850}>{n.title}</Typography>{!n.read&&<Chip size="small" label="Nouveau" color="primary"/>}</Stack><Typography color="text.secondary">{n.message}</Typography><Typography variant="caption" color="text.secondary">{n.project?.name||""}{n.createdAt?` · ${new Date(n.createdAt).toLocaleString()}`:""}</Typography></Box>{!n.read&&<IconButton onClick={()=>read(n)} title="Marquer comme lu"><MarkEmailUnreadOutlinedIcon/></IconButton>}{n.taskId&&<Button size="small" endIcon={<ArrowForwardIcon/>} onClick={()=>read(n)}>Ouvrir</Button>}</Stack>{i<rows.length-1&&<Divider/>}</React.Fragment>):<Box sx={{p:6,textAlign:"center"}}><Typography variant="h6" fontWeight={800}>Vous êtes à jour</Typography><Typography color="text.secondary">Aucune notification ne correspond à cette vue.</Typography></Box>}</CardContent></Card></Stack>;
}
