import React, { useMemo, useState } from "react";
import { Avatar, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import DeleteIcon from "@mui/icons-material/Delete";
import SendIcon from "@mui/icons-material/Send";

const statusLabel = { todo: "À faire", in_progress: "En cours", done: "Terminée" };
const priorityLabel = { high: "Haute", medium: "Moyenne", low: "Basse" };
const priorityColor = { high: "error", medium: "warning", low: "success" };

export default function TaskDetailDialog({ task, open, onClose, users, comments, currentUser, onAssign, onComment, onDelete }) {
  const [text, setText] = useState("");
  const assignee = users.find(u => String(u.id) === String(task?.assigneeId));
  const safeComments = useMemo(() => Array.isArray(comments) ? comments : [], [comments]);
  if (!task) return null;
  const submit = e => { e.preventDefault(); if (!text.trim()) return; onComment(text.trim()); setText(""); };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h6" fontWeight={900}>{task.title}</Typography><Stack direction="row" spacing={.75} sx={{ mt: 1 }}><Chip size="small" label={statusLabel[task.status] || task.status}/><Chip size="small" label={priorityLabel[task.priority] || task.priority} color={priorityColor[task.priority] || "default"}/>{task.dueDate && <Chip size="small" variant="outlined" label={task.dueDate}/>}</Stack></Box><IconButton color="error" onClick={() => { onDelete(task.id); onClose(); }}><DeleteIcon/></IconButton></Stack></DialogTitle><DialogContent dividers><Stack spacing={3}><Box><Typography variant="subtitle2" fontWeight={800}>Description</Typography><Typography color="text.secondary" sx={{ mt: .5, whiteSpace: "pre-wrap" }}>{task.description || "Aucune description."}</Typography></Box><Box><Typography variant="subtitle2" fontWeight={800} sx={{ mb: 1 }}>Responsable</Typography><Stack direction="row" spacing={1.5} alignItems="center"><Select size="small" value={task.assigneeId || ""} onChange={e => onAssign(task.id, e.target.value)} sx={{ minWidth: 260 }}><MenuItem value="">Non assignée</MenuItem>{users.map(u => <MenuItem key={u.id} value={u.id}>{u.name} — {u.email}</MenuItem>)}</Select>{assignee && <Chip avatar={<Avatar>{assignee.name?.[0]}</Avatar>} label={assignee.name}/>}</Stack></Box><Divider/><Box><Typography variant="subtitle2" fontWeight={800} sx={{ mb: 1.5 }}>Commentaires ({safeComments.length})</Typography><Stack spacing={1.5}>{safeComments.map(c => { const author = users.find(u => String(u.id) === String(c.userId)); return <Box key={c.id} sx={{ p: 1.5, borderRadius: 2, bgcolor: "action.hover" }}><Stack direction="row" spacing={1} alignItems="center"><Avatar sx={{ width: 28, height: 28 }}>{author?.name?.[0] || "U"}</Avatar><Typography fontWeight={700}>{author?.name || "Utilisateur"}</Typography><Typography variant="caption" color="text.secondary">{new Date(c.createdAt).toLocaleString()}</Typography></Stack><Typography variant="body2" sx={{ mt: .75, whiteSpace: "pre-wrap" }}>{c.text}</Typography></Box>})}{!safeComments.length && <Typography variant="body2" color="text.secondary">Aucun commentaire pour le moment.</Typography>}</Stack><form onSubmit={submit}><Stack direction="row" spacing={1} sx={{ mt: 2 }}><TextField fullWidth size="small" placeholder="Écrire un commentaire…" value={text} onChange={e => setText(e.target.value)}/><Button type="submit" variant="contained" endIcon={<SendIcon/>}>Envoyer</Button></Stack></form></Box></Stack></DialogContent><DialogActions><Button onClick={onClose}>Fermer</Button></DialogActions></Dialog>;
}
