import React, { useEffect, useMemo, useState } from "react";
import { Button, Chip, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import FilterAltOutlinedIcon from "@mui/icons-material/FilterAltOutlined";
import BookmarkBorderIcon from "@mui/icons-material/BookmarkBorder";
import RestartAltIcon from "@mui/icons-material/RestartAlt";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import { createSavedViewApi, deleteSavedViewApi, getSavedViewsApi } from "../api";

export default function TaskFilters({ projects=[], users=[], value, onChange, storageKey="taskflow-task-views" }) {
  const [savedName,setSavedName]=useState(""); const [views,setViews]=useState([]);
  const filter=value||{search:"",status:"all",priority:"all",project:"all",assignee:"all",due:"all"};
  const activeCount=useMemo(()=>Object.entries(filter).filter(([k,v])=>k!=="search"&&v!=="all" || k==="search"&&v).length,[filter]);
  useEffect(()=>{ getSavedViewsApi("tâches").then(r=>setViews(r.data||[])).catch(()=>{ try{setViews(JSON.parse(localStorage.getItem(storageKey)||"[]"));}catch(_){} }); },[storageKey]);
  const set=(key,val)=>onChange({...filter,[key]:val});
  const reset=()=>onChange({search:"",status:"all",priority:"all",project:"all",assignee:"all",due:"all"});
  const saveView=async()=>{const name=savedName.trim();if(!name)return;try{const r=await createSavedViewApi({name,resource:"tâches",filters:filter});setViews(v=>[r.data,...v]);setSavedName("");}catch(_){const next=[...views,{name,filters:filter}];setViews(next);localStorage.setItem(storageKey,JSON.stringify(next));setSavedName("");}};
  const applyView=name=>{const v=views.find(x=>x.name===name);if(v?.filters)onChange(v.filters);};
  const removeView=async id=>{try{await deleteSavedViewApi(id);setViews(v=>v.filter(x=>x.id!==id));}catch(_){}};
  return <Paper variant="outlined" sx={{p:1.5,borderRadius:3}}><Stack spacing={1.5}><Stack direction={{xs:"column",md:"row"}} spacing={1} alignItems={{md:"center"}}><Stack direction="row" spacing={1} alignItems="center"><FilterAltOutlinedIcon color="primary"/><Typography fontWeight={850}>Filtres</Typography>{activeCount>0&&<Chip size="small" label={`${activeCount} actifs`}/>}</Stack><TextField size="small" placeholder="Rechercher des tâches…" value={filter.search} onChange={e=>set("search",e.target.value)} sx={{minWidth:{md:240}}}/><Select size="small" value={filter.status} onChange={e=>set("status",e.target.value)}><MenuItem value="all">Tous les statuts</MenuItem><MenuItem value="todo">À faire</MenuItem><MenuItem value="in_progress">En cours</MenuItem><MenuItem value="done">Terminée</MenuItem></Select><Select size="small" value={filter.priority} onChange={e=>set("priority",e.target.value)}><MenuItem value="all">Toutes les priorités</MenuItem><MenuItem value="high">Haute</MenuItem><MenuItem value="medium">Moyenne</MenuItem><MenuItem value="low">Basse</MenuItem></Select></Stack>
  <Stack direction={{xs:"column",md:"row"}} spacing={1}><Select size="small" value={filter.project} onChange={e=>set("project",e.target.value)} sx={{minWidth:180}}><MenuItem value="all">Tous les projets</MenuItem>{projects.map(p=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</Select><Select size="small" value={filter.assignee} onChange={e=>set("assignee",e.target.value)} sx={{minWidth:180}}><MenuItem value="all">Tous les responsables</MenuItem><MenuItem value="unassigned">Non assignée</MenuItem>{users.map(u=><MenuItem key={u.id} value={u.id}>{u.name}</MenuItem>)}</Select><Select size="small" value={filter.due} onChange={e=>set("échéance",e.target.value)} sx={{minWidth:180}}><MenuItem value="all">Toute échéance</MenuItem><MenuItem value="overdue">En retard</MenuItem><MenuItem value="today">À échéance aujourd’hui</MenuItem><MenuItem value="upcoming">7 prochains jours</MenuItem><MenuItem value="none">Sans échéance</MenuItem></Select><TextField size="small" placeholder="Enregistrer la vue…" value={savedName} onChange={e=>setSavedName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&saveView()} sx={{flex:1}}/><Button size="small" startIcon={<BookmarkBorderIcon/>} onClick={saveView} disabled={!savedName.trim()}>Enregistrer</Button>{views.length>0&&<Select size="small" displayEmpty value="" onChange={e=>applyView(e.target.value)} sx={{minWidth:150}}><MenuItem value="">Vues enregistrées</MenuItem>{views.map(v=><MenuItem key={v.id||v.name} value={v.name}>{v.name}</MenuItem>)}</Select>}<Button size="small" startIcon={<RestartAltIcon/>} onClick={reset}>Réinitialiser</Button></Stack>
  {views.length>0&&<Stack direction="row" spacing={.5} flexWrap="wrap">{views.map(v=>v.id?<Chip key={v.id} size="small" label={v.name} onDelete={()=>removeView(v.id)} deleteIcon={<DeleteOutlineIcon/>}/>:null)}</Stack>}</Stack></Paper>;
}
